kind: Service
apiVersion: v1
metadata:
  name: greenhouse-service
  namespace: falco
spec:
  selector:
    app: greenhouse
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-greenhouse
  namespace: falco
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      containers:
      - name: maven
        image: container.rancher.ardfactory.com/example-greenhouse:10
        envFrom:
        - secretRef:
            name: sample
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: try2
  namespace: falco
  selfLink: /apis/extensions/v1beta1/namespaces/falco/ingresses/try2
spec:
  rules:
  - host: try2.rancher.ardfactory.com
    http:
      paths:
      - backend:
          serviceName: greenhouse-service
          servicePort: 8080
